import Head from "next/head";
import Image from "next/image";
import { Component } from "react";
import Header from "../components/Header.js";
import Exmple from "../components/Exmple.js";
import styles from "../styles/Home.module.css";
import { Box } from "@mui/material";

import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>surVapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url(https://fonts.googleapis.com/css2?family=Kanit:wght@300&display=swap);
        </style>
      </Head>

      <Box sx={{ dispaly: "flex", justifyContent: "flex-end" }}>
        {/* <Exmple /> */}
      </Box>
    </>
  );
}
